### ISSUE TITLE
Error occurred while enabling XgpLottery2 v2.0.0 

### ISSUE THREAD

**Issue by FortyTwoCn** [xgpjun/XgpLottery#4]
CatServer 1.16.5

[12:51:24] [Server thread/ERROR]: Error occurred while enabling XgpLottery2 v2.0.0 (Is it up to date?)
 java.lang.NoSuchMethodException: net.minecraft.item.ItemStack.<init>(net.minecraft.nbt.CompoundNBT)
        at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_172]
        at java.lang.Class.getConstructor(Unknown Source) ~[?:1.8.0_172]
        at cn.xgpjun.xgplottery2.nms.V1_16Below.init(NMSWrapper.kt:41) ~[?:?]
        at cn.xgpjun.xgplottery2.manager.NMSManager.register(NMSManager.kt:31) ~[?:?]
        at cn.xgpjun.xgplottery2.XgpLottery.onEnable(XgpLottery.kt:31) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[?:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:412) ~[?:1.16.5-69069a9c]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:323) ~[?:1.16.5-69069a9c]
        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:439) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:345) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:218) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:737) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]

**Comment by FortyTwoCn** [comment]
> xgplottery2 help 62a79341-7adb-4791-a1c4-d829f237f033
>
[15:48:22] [Server thread/INFO]: plugin is disabled!
